import turtle
def create_field():
    # window configuration
    win = turtle.Screen()
    win.bgcolor('dark green')
    win.title('FIFA: Primitive Age')
    win.tracer(0)
    w, h = 1224, 700

    # map design
    boundary = turtle.Turtle()
    boundary.color('white')
    boundary.speed(0)
    boundary.pensize(5)
    boundary.sety(-95 / 100 * h / 2)
    boundary.sety(95 / 100 * h / 2)
    boundary.setx(-95 / 100 * w / 2)
    boundary.setx(95 / 100 * w / 2)
    boundary.sety(-95 / 100 * h / 2)
    boundary.setx(-95 / 100 * w / 2)
    boundary.sety(95 / 100 * h / 2)
    boundary.pu()
    boundary.goto(0, -30)
    boundary.pd()
    boundary.circle(30)
    boundary.pu()
    boundary.goto(-95 / 100 * w / 2, 3 / 10 * h / 2)
    boundary.pd()
    boundary.setx(-8 / 10 * w / 2)
    boundary.color('green')
    boundary.sety(-3 / 10 * h / 2)
    boundary.color('white')
    boundary.setx(-95 / 100 * w / 2)
    boundary.pu()
    boundary.goto(95 / 100 * w / 2, 3 / 10 * h / 2)
    boundary.pd()
    boundary.setx(8 / 10 * w / 2)
    boundary.color('green')
    boundary.sety(-3 / 10 * h / 2)
    boundary.color('white')
    boundary.setx(95 / 100 * w / 2)
    boundary.hideturtle()
    boundary.pu()

    # goal pen
    goalpen = turtle.Turtle()
    goalpen.ht()
    goalpen.penup()
    goalpen.color('white')
